---
- name: set timezone '{{ region }}/{{ city }}'
  timezone: 
    name: '{{ region }}/{{ city }}'

- name: Set hostname to the host
  hostname:
    name: '{{ inventory_hostname }}'

- block:
  - name: Create a swap file
    shell: fallocate -l {{ swap_size }} "{{ swap_location }}"
    args:
      creates: "{{ swap_location }}"
  
  - name: Set the correct permisions
    file: 
      path: "{{ swap_location }}"
      owner: root
      group: root
      mode: '0600'
  
  - name: Make the file a swap file
    shell: mkswap "{{ swap_location }}"
    when: ansible_facts.swapfree_mb == 0

  - name: Enable the swap file
    shell: swapon "{{ swap_location }}"
    when: ansible_facts.swapfree_mb == 0

  - name: Add the swap file to fstab
    mount: 
      name: none
      src: "{{ swap_location }}"
      fstype: swap
      opts: sw
      passno: 0
      dump: 0
      state: present