---
- name: set timezone to Europe/Moscow
  timezone: 
    name: Europe/Moscow

- block:
  - name: Create a swap file
    shell: fallocate -l {{ swap_size }} /swapfile
    args:
      creates: /swapfile
  
  - name: Set the correct permisions
    file: 
      path: /swapfile
      owner: root
      group: root
      mode: '0600'
  
  - name: Make the file a swap file
    shell: mkswap /swapfile
    when: ansible_facts.swapfree_mb == 0

  - name: Enable the swap file
    shell: swapon /swapfile
    when: ansible_facts.swapfree_mb == 0

  - name: Add the swap file to fstab
    mount: 
      name: none
      src: /swapfile
      fstype: swap
      opts: sw
      passno: 0
      dump: 0
      state: present